#!/usr/bin/env bun
// build-names.js — process vendored census + SSA data into js/names.js

import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = dirname(__dirname);
const DATA = join(ROOT, 'data');
const OUT = join(ROOT, 'js', 'names.js');

// --- Surnames (Census 2010) ---
// CSV: name,rank,count,prop100k,...
const surnameCSV = readFileSync(join(DATA, 'census-surnames', 'Names_2010Census.csv'), 'utf-8');
const surnameLines = surnameCSV.trim().split('\n').slice(1); // skip header

const surnames = [];
for (const line of surnameLines) {
  const cols = line.split(',');
  const name = cols[0].trim();
  const rank = parseInt(cols[1], 10);
  const count = parseInt(cols[2], 10);
  // Skip catch-all row (rank 0) and invalid entries
  if (!name || rank <= 0 || isNaN(count) || count <= 0) continue;
  // Title case
  const titled = name.charAt(0).toUpperCase() + name.slice(1).toLowerCase();
  surnames.push([titled, count]);
}

// Sort by count descending
surnames.sort((a, b) => b[1] - a[1]);

console.log(`Surnames: ${surnames.length} entries`);
console.log(`  Top: ${surnames[0][0]} (${surnames[0][1]}), ${surnames[1][0]} (${surnames[1][1]})`);

// --- First names (SSA baby names) ---
// Files: yobYYYY.txt — name,gender,count per line
// Aggregate across 1960-2005 to cover twenties-forties age stages
const ssaDir = join(DATA, 'ssa-babynames');
const ssaFiles = readdirSync(ssaDir).filter(f => f.startsWith('yob') && f.endsWith('.txt'));

const firstNameCounts = new Map();

for (const file of ssaFiles) {
  const yearMatch = file.match(/yob(\d+)\.txt/);
  if (!yearMatch) continue;
  const year = parseInt(yearMatch[1], 10);
  if (year < 1960 || year > 2005) continue;

  const content = readFileSync(join(ssaDir, file), 'utf-8');
  for (const line of content.trim().split('\n')) {
    const parts = line.split(',');
    if (parts.length < 3) continue;
    const name = parts[0].trim();
    const count = parseInt(parts[2], 10);
    if (!name || isNaN(count)) continue;

    // Accumulate across years and genders
    const existing = firstNameCounts.get(name) || 0;
    firstNameCounts.set(name, existing + count);
  }
}

// Convert to sorted array
const firstNames = [];
for (const [name, count] of firstNameCounts) {
  if (count > 0) firstNames.push([name, count]);
}

// Sort by count descending
firstNames.sort((a, b) => b[1] - a[1]);

console.log(`First names: ${firstNames.length} entries`);
console.log(`  Top: ${firstNames[0][0]} (${firstNames[0][1]}), ${firstNames[1][0]} (${firstNames[1][1]})`);

// --- Filter by minimum frequency ---
// Drop names too rare to meaningfully appear — keeps file reasonable
// while preserving the full frequency distribution of real names.
// Surname threshold: count >= 1000 (covers ~90% of population by weight)
// First name threshold: count >= 500 across the 46-year window
const filteredFirst = firstNames.filter(([, w]) => w >= 500);
const filteredLast = surnames.filter(([, w]) => w >= 1000);

console.log(`Filtered to: ${filteredFirst.length} first (>= 500), ${filteredLast.length} last (>= 1000)`);

// --- Write output ---
// Compact format: arrays of [name, weight] pairs
const output = `// names.js — generated by scripts/build-names.js
// US Census 2010 surnames + SSA baby names (1960-2005)
// Do not edit manually.

const NameData = {
  first: ${JSON.stringify(filteredFirst)},
  last: ${JSON.stringify(filteredLast)},
};
`;

writeFileSync(OUT, output);
const size = readFileSync(OUT).length;
console.log(`\nWritten: ${OUT}`);
console.log(`  File size: ${(size / 1024).toFixed(0)} KB`);
